name: GitHub Pages

on: [push, pull_request]

defaults:
  run:
    working-directory: docs

jobs:
  deploy:
    runs-on: ubuntu-20.04

    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: BRANCH_NAME
        run: echo ${{ github.head_ref }}

      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.80.0'
          extended: true
      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        # If you're changing the branch from ${{ github.head_ref }},
        # also change the `${{ github.head_ref }}` in `refs/heads/${{ github.head_ref }}`
        # below accordingly.
        if: ${{ github.ref == 'refs/heads/${{ github.head_ref }}' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/public